[project]
name = "blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "monsterui>=1.0.36",
    "python-fasthtml>=0.12.37",
]

[tool.uv.workspace]
members = ["my_blog"]
